import React, { useState, useEffect } from "react";
import OrderTable from "../../components/OrderTable";
import axios from "axios";

const ManageOrder = () => {
  const orders = [
    {
      id: 1,
      orderId: "#1002",
      date: "11 Feb, 2024",
      customer: "Wade Warren",
      payment: "Pending",
      total: 20.0,
      delivery: "N/A",
      items: 2,
      fulfillment: "Unfulfilled",
    },
    {
      id: 2,
      orderId: "#1004",
      date: "13 Feb, 2024",
      customer: "Esther Howard",
      payment: "Success",
      total: 22.0,
      delivery: "N/A",
      items: 3,
      fulfillment: "Fulfilled",
    },
    {
      id: 3,
      orderId: "#1005",
      date: "15 Feb, 2024",
      customer: "Darlene Robertson",
      payment: "Success",
      total: 35.0,
      delivery: "N/A",
      items: 5,
      fulfillment: "Closed",
    },
    {
      id: 4,
      orderId: "#1006",
      date: "17 Feb, 2024",
      customer: "Jacob Jones",
      payment: "Pending",
      total: 18.0,
      delivery: "N/A",
      items: 2,
      fulfillment: "Open",
    },
    {
      id: 5,
      orderId: "#1007",
      date: "19 Feb, 2024",
      customer: "Ronald Richards",
      payment: "Failed",
      total: 25.0,
      delivery: "N/A",
      items: 3,
      fulfillment: "Unpaid",
    },
    {
      id: 6,
      orderId: "#1008",
      date: "21 Feb, 2024",
      customer: "Leslie Alexander",
      payment: "Success",
      total: 40.0,
      delivery: "N/A",
      items: 6,
      fulfillment: "Fulfilled",
    },
    {
      id: 7,
      orderId: "#1009",
      date: "23 Feb, 2024",
      customer: "Guy Hawkins",
      payment: "Pending",
      total: 30.0,
      delivery: "N/A",
      items: 4,
      fulfillment: "Unfulfilled",
    },
    {
      id: 8,
      orderId: "#1010",
      date: "25 Feb, 2024",
      customer: "Eleanor Pena",
      payment: "Success",
      total: 50.0,
      delivery: "N/A",
      items: 8,
      fulfillment: "Closed",
    },
    {
      id: 9,
      orderId: "#1011",
      date: "27 Feb, 2024",
      customer: "Marvin McKinney",
      payment: "Success",
      total: 22.0,
      delivery: "N/A",
      items: 3,
      fulfillment: "Open",
    },
    {
      id: 10,
      orderId: "#1012",
      date: "01 Mar, 2024",
      customer: "Kathryn Murphy",
      payment: "Failed",
      total: 20.0,
      delivery: "N/A",
      items: 2,
      fulfillment: "Unpaid",
    },
    {
      id: 11,
      orderId: "#1013",
      date: "03 Mar, 2024",
      customer: "Cody Fisher",
      payment: "Success",
      total: 55.0,
      delivery: "N/A",
      items: 9,
      fulfillment: "Fulfilled",
    },
    {
      id: 12,
      orderId: "#1014",
      date: "05 Mar, 2024",
      customer: "Courtney Henry",
      payment: "Pending",
      total: 10.0,
      delivery: "N/A",
      items: 1,
      fulfillment: "Unfulfilled",
    },
    {
      id: 13,
      orderId: "#1015",
      date: "07 Mar, 2024",
      customer: "Devon Lane",
      payment: "Success",
      total: 45.0,
      delivery: "N/A",
      items: 7,
      fulfillment: "Closed",
    },
    {
      id: 14,
      orderId: "#1016",
      date: "09 Mar, 2024",
      customer: "Arlene McCoy",
      payment: "Pending",
      total: 28.0,
      delivery: "N/A",
      items: 4,
      fulfillment: "Open",
    },
    {
      id: 15,
      orderId: "#1017",
      date: "11 Mar, 2024",
      customer: "Jerome Bell",
      payment: "Failed",
      total: 33.0,
      delivery: "N/A",
      items: 5,
      fulfillment: "Unpaid",
    },
    {
      id: 16,
      orderId: "#1018",
      date: "13 Mar, 2024",
      customer: "Glenna Reichert",
      payment: "Success",
      total: 60.0,
      delivery: "N/A",
      items: 10,
      fulfillment: "Fulfilled",
    },
    {
      id: 17,
      orderId: "#1019",
      date: "15 Mar, 2024",
      customer: "Howard Hicks",
      payment: "Pending",
      total: 15.0,
      delivery: "N/A",
      items: 2,
      fulfillment: "Unfulfilled",
    },
    {
      id: 18,
      orderId: "#1020",
      date: "17 Mar, 2024",
      customer: "Dianne Russell",
      payment: "Success",
      total: 38.0,
      delivery: "N/A",
      items: 6,
      fulfillment: "Closed",
    },
    {
      id: 19,
      orderId: "#1021",
      date: "19 Mar, 2024",
      customer: "Brandon Murphy",
      payment: "Pending",
      total: 12.0,
      delivery: "N/A",
      items: 2,
      fulfillment: "Open",
    },
    {
      id: 20,
      orderId: "#1022",
      date: "21 Mar, 2024",
      customer: "Charlotte Stewart",
      payment: "Failed",
      total: 26.0,
      delivery: "N/A",
      items: 3,
      fulfillment: "Unpaid",
    },
    {
      id: 21,
      orderId: "#1023",
      date: "23 Mar, 2024",
      customer: "Kenneth Bridges",
      payment: "Success",
      total: 48.0,
      delivery: "N/A",
      items: 7,
      fulfillment: "Fulfilled",
    },
    {
      id: 22,
      orderId: "#1024",
      date: "25 Mar, 2024",
      customer: "Mabel Simmons",
      payment: "Pending",
      total: 17.0,
      delivery: "N/A",
      items: 3,
      fulfillment: "Unfulfilled",
    },
    {
      id: 23,
      orderId: "#1025",
      date: "27 Mar, 2024",
      customer: "Savannah Nguyen",
      payment: "Success",
      total: 29.0,
      delivery: "N/A",
      items: 4,
      fulfillment: "Closed",
    },
    {
      id: 24,
      orderId: "#1026",
      date: "29 Mar, 2024",
      customer: "Harvey Mitchell",
      payment: "Pending",
      total: 20.0,
      delivery: "N/A",
      items: 3,
      fulfillment: "Open",
    },
    {
      id: 25,
      orderId: "#1027",
      date: "31 Mar, 2024",
      customer: "Nancy Tran",
      payment: "Failed",
      total: 19.0,
      delivery: "N/A",
      items: 2,
      fulfillment: "Unpaid",
    },
    {
      id: 26,
      orderId: "#1028",
      date: "02 Apr, 2024",
      customer: "Curtis Gray",
      payment: "Success",
      total: 24.0,
      delivery: "N/A",
      items: 4,
      fulfillment: "Fulfilled",
    },
    {
      id: 27,
      orderId: "#1029",
      date: "04 Apr, 2024",
      customer: "Denise Chapman",
      payment: "Pending",
      total: 10.0,
      delivery: "N/A",
      items: 1,
      fulfillment: "Unfulfilled",
    },
    {
      id: 28,
      orderId: "#1030",
      date: "06 Apr, 2024",
      customer: "Marjorie Powell",
      payment: "Success",
      total: 39.0,
      delivery: "N/A",
      items: 6,
      fulfillment: "Closed",
    },
    {
      id: 29,
      orderId: "#1031",
      date: "08 Apr, 2024",
      customer: "Erik Meyer",
      payment: "Pending",
      total: 13.0,
      delivery: "N/A",
      items: 2,
      fulfillment: "Open",
    },
    {
      id: 30,
      orderId: "#1032",
      date: "10 Apr, 2024",
      customer: "Jamie Thompson",
      payment: "Failed",
      total: 27.0,
      delivery: "N/A",
      items: 3,
      fulfillment: "Unpaid",
    },
  ];

  const [orders2, setOrders] = useState([]);
  useEffect(() => {
    const fetchOrders = async () => {
      try {
        const response = await axios.get("/api/orders"); // Replace with your API endpoint
        setOrders(response.data);
      } catch (error) {
        console.error("Error fetching orders:", error);
      }
    };

    fetchOrders();
  }, []);

  console.log(orders2);
  return (
    <div>
      <h1 className=" text-3xl font-semibold text-gray-800 my-5">Orders</h1>
      <OrderTable orders={orders} />
    </div>
  );
};

export default ManageOrder;
